## TablaMaestra de Excel a csv

In [20]:
import pandas as pd
import numpy as np
df=pd.read_excel(r"C:\Users\horacio.brites\OneDrive - ARAUCO\DW Qlik\DataExcels\TablaMaestra.xlsx",sheet_name="TablaMaestra")
Map = {
    'PF': 'MA',
    'BK': 'RP',
    'BL': 'RP',
    'MA': 'MA',
    'CP': 'CP'
}

df.loc[:, "FamiliaPostiza"] = np.where(
    df["Familia"] == "MU",
    np.where(
        df["Terminación"] == "RGH",
        "MU",
        "MUX"
    ),
    df["Familia"].map(Map)
)

df["AnchoPPCalc"] = df["AnchoPPCalc"].fillna(0)
df["Escuadria"] = (
    df["FamiliaPostiza"].astype(str)
    + " "
    + df["EspesorPPCalc"].astype(int).astype(str)
    + "x"
    + df["AnchoPPCalc"].astype(int).astype(str)
)
df['Status']=True
df.to_csv(r"C:\Users\horacio.brites\OneDrive - ARAUCO\DW Qlik\DataExcels\TablaMaestra.csv",index=False,encoding="utf-8",sep=";")

## Nuevos Registros

In [30]:
import pandas as pd
import numpy as np
# ================== Funciones ================================
def parse_numero(serie):
    return (
        serie
        .astype(str)
        .str.replace('.', '', regex=False)   # elimina separador de miles
        .str.replace(',', '.', regex=False)   # coma → punto decimal
        .pipe(pd.to_numeric, errors='coerce')
    )
# ============================ PM_Aserradero2 =============================
df1 = pd.read_csv(r"C:\Users\horacio.brites\OneDrive - ARAUCO\DW Qlik\DataExcels\Maestro de Maeriales.txt",sep="\t",encoding="latin-1",
    skiprows=3,          # saltea título + línea en blanco + encabezado de columnas vacío
    header=0,            # la fila 4 (índice 3) es el header real
    skipinitialspace=True,
    dtype=str            # todo como string primero, para no perder nada
)

df1.columns = df1.columns.str.strip()
df1 = df1.dropna(subset=["Objeto"])
df1["Objeto"] = df1["Objeto"].str.strip()
df1 = df1[df1["Objeto"] != ""]
df1=df1[['Objeto', 'Denomin.', 'Tipo de madera', 'Familia','Calidad', 'Terminación','Grado', 'Espesor', 'Ancho', 'Largo']]
print(df1[df1['Objeto']=="1524107"])

#=========================== PM_Aserradero ===============================================
df2 = pd.read_csv(r"C:\Users\horacio.brites\OneDrive - ARAUCO\DW Qlik\DataExcels\Maestro de Maeriales2.txt",sep="\t",encoding="latin-1",
    skiprows=3,          # saltea título + línea en blanco + encabezado de columnas vacío
    header=0,            # la fila 4 (índice 3) es el header real
    skipinitialspace=True,
    dtype=str            # todo como string primero, para no perder nada
)
df2.columns = df2.columns.str.strip()
df2 = df2.dropna(subset=["Objeto"])
df2["Objeto"] = df2["Objeto"].str.strip()
df2 = df2[df2["Objeto"] != ""]
df2=df2[['Objeto', 'Denomin.', 'Tipo de madera', 'Familia','Calidad', 'Terminación','Grado', 'Espesor', 'Ancho', 'Largo']]
#=================================== Blanks =========================================
df3 = pd.read_csv(
    r"C:\Users\horacio.brites\OneDrive - ARAUCO\DW Qlik\DataExcels\Maestro de Materiales_blanks.txt",
    sep="\t",
    encoding="latin-1",
    skiprows=3,
    dtype=str
)
df3.columns = df3.columns.str.strip()
df3 = df3.dropna(subset=["Objeto"])
df3["Objeto"] = df3["Objeto"].str.strip()
df3 = df3[df3["Objeto"] != ""]
df3=df3[['Objeto', 'Denomin.', 'Tipo de madera', 'Familia','Calidad', 'Terminación','Grado', 'Espesor', 'Ancho', 'Largo']]
#======================================= Blocks ==========================================
df4 = pd.read_csv(
    r"C:\Users\horacio.brites\OneDrive - ARAUCO\DW Qlik\DataExcels\Maestro de Materiales_block.txt",
    sep="\t",
    encoding="latin-1",
    skiprows=3,
    dtype=str
)
df4.columns = df4.columns.str.strip()
df4 = df4.dropna(subset=["Objeto"])
df4["Objeto"] = df4["Objeto"].str.strip()
df4 = df4[df4["Objeto"] != ""]
df4=df4[['Objeto', 'Denomin.', 'Tipo de madera', 'Familia','Calidad', 'Terminación','Grado', 'Espesor', 'Ancho', 'Largo']]

#================================== df_base ===============================
df_con = pd.concat([df1, df2, df3, df4], ignore_index=True)
df_con["Terminación"] = df_con["Terminación"].replace({"RG": "RGH"})
df_con['Ancho'] = df_con['Ancho'].fillna(0)
df_base = pd.read_csv(r"C:\Users\horacio.brites\OneDrive - ARAUCO\DW Qlik\DataExcels\BDBase.csv",encoding="utf-8",dtype=str)
df_nuevos = df_con[~df_con["Objeto"].isin(df_base["Objeto"])].copy()
df_nuevos[['Espesor', 'Ancho', 'Largo']] = df_nuevos[['Espesor', 'Ancho', 'Largo']].apply(parse_numero)
#df_nuevos[['Espesor', 'Ancho', 'Largo']] = (df_nuevos[['Espesor', 'Ancho', 'Largo']].replace(',', '.', regex=True).apply(pd.to_numeric, errors='coerce'))
df_nuevos

       Objeto                      Denomin. Tipo de madera Familia Calidad  \
9754  1524107  PTCMAPMRGSEG1 15x86x4270 528              C      MA      PM

     Terminación Grado Espesor   Ancho      Largo
9754          RG    G1  15,000  86,000  4.270,000

,Objeto,Denomin.,Tipo de madera,Familia,Calidad,Terminación,Grado,Espesor,Ancho,Largo
5,1205715,PPCMASPRGSESD 23x148xRL,C,MA,SP,RGH,SD,23.0,148.0,NaN
94,1205835,PPCMASPRGVESD 28x104x4880,C,MA,SP,RGH,SD,28.0,104.0,NaN
1181,1207980,PPLMUPRRGVESD 18x104xRL,L,MU,PR,RGH,SD,18.0,104.0,NaN
1862,1209155,PPCMASPRGVESD 23x148x6+6,C,MA,SP,RGH,SD,23.0,148.0,NaN
2148,1209732,PPLMUMXRGSESD 23x151xRL,L,MU,MX,RGH,SD,23.0,151.0,NaN
2250,1209896,PPCCPUSRGVESD 18x83x11,C,CP,US,RGH,SD,18.0,83.0,NaN
2315,1210019,PPLRPPCRGSESD 38x119xRL,L,RP,PC,RGH,SD,38.0,119.0,NaN
2333,1210082,PPCCPPARGSESD 16x140x3+3+3,C,CP,PA,RGH,SD,16.0,140.0,NaN
7384,1521007,PTLMUMERGSEEX 17x125x2440 312,L,MU,ME,RGH,EX,17.0,125.0,2440.0
9933,1524350,PTCMAPMRGSEG1 17x125x2440 312,C,MA,PM,RGH,G1,17.0,125.0,2440.0
10279,1524911,PTCCPUSRGSEG1 17x80x1100 893,C,CP,US,RGH,G1,17.0,80.0,1100.0
15086,1500752,PTCPFMAS4SEG2 1x6x8 280,C,PF,MA,S4,G2,22.0,147.0,2440.0

## Divide los materiales en PP y PT

In [31]:
df_nuevos_PT=df_nuevos[df_nuevos['Denomin.'].str.startswith("PT")].copy()
df_nuevos_PP=df_nuevos[df_nuevos['Denomin.'].str.startswith("PP")].copy()
df_nuevos_PT

,Objeto,Denomin.,Tipo de madera,Familia,Calidad,Terminación,Grado,Espesor,Ancho,Largo
7384,1521007,PTLMUMERGSEEX 17x125x2440 312,L,MU,ME,RGH,EX,17.0,125.0,2440.0
9933,1524350,PTCMAPMRGSEG1 17x125x2440 312,C,MA,PM,RGH,G1,17.0,125.0,2440.0
10279,1524911,PTCCPUSRGSEG1 17x80x1100 893,C,CP,US,RGH,G1,17.0,80.0,1100.0
15086,1500752,PTCPFMAS4SEG2 1x6x8 280,C,PF,MA,S4,G2,22.0,147.0,2440.0

## Codificiacion de productos terminados

In [32]:
#Materiales que comienzan con PT
#1- EspesorPPCalc
df_nuevos_PT.loc[:, "EspesorPPCalc"] = np.where(
    df_nuevos_PT["Terminación"] == "RGH",
    round(df_nuevos_PT["Espesor"] * (1 + 0.035), 0),

    np.where(
        df_nuevos_PT["Terminación"].isin(["S2", "S4", "R4"]),
        round((df_nuevos_PT["Espesor"] + 2*1.5 + 0.2*2) * (1 + 0.035), 0),

        np.where(
            df_nuevos_PT["Terminación"].isin(["S1", "S3"]),
            round((df_nuevos_PT["Espesor"] + 1.5 + 0.2*1) * (1 + 0.035), 0),
            np.nan
        )
    )
)


#2- AnchoPPCalc
df_nuevos_PT.loc[:, "AnchoPPCalc"] = np.where(
    (df_nuevos_PT["Ancho"] == 0) | (df_nuevos_PT["Ancho"].isna()),
    0,

    np.where(
        (df_nuevos_PT["Terminación"] == "RGH") & (df_nuevos_PT["Ancho"] > 120),
        round(df_nuevos_PT["Ancho"] * (1 + 0.04), 0),

        np.where(
            df_nuevos_PT["Terminación"].isin(["RGH", "S1", "S2"]),
            round(df_nuevos_PT["Ancho"] * (1 + 0.035), 0),

            np.where(
                df_nuevos_PT["Terminación"].isin(["S3", "S4", "R4"]),
                round((df_nuevos_PT["Ancho"] + 2 * 1.5 + 0.2 * 2) * (1 + 0.035), 0),
                np.nan
            )
        )
    )
)

#3-LargoPPCalc


map_largo = {
    1014: 3050,
    936: 3050,
    1217: 3660,
    1000: 3050,
    1100: 3355,
    1200: 3660,
    1218: 3660,
    915: 3050,
    1220: 3660,
    1118: 4575
}

df_nuevos_PT["Largo"] = pd.to_numeric(df_nuevos_PT["Largo"], errors="coerce")

df_nuevos_PT["LargoPPCalc"] = np.where(
    df_nuevos_PT["Familia"].isin(["BK", "MU"]),
    0,

    np.where(
        df_nuevos_PT["Familia"] == "CP",
        df_nuevos_PT["Largo"].map(map_largo),

        np.where(
            (df_nuevos_PT["Tipo de madera"] == "C") & (df_nuevos_PT["Largo"] <= 2440),
            df_nuevos_PT["Largo"] * 2,
            df_nuevos_PT["Largo"]
        )
    )
)

#4-Kerf
df_nuevos_PT.loc[:, "Kerf"] = np.where(
    (df_nuevos_PT["Tipo de madera"] == "C") & (df_nuevos_PT["Largo"] == 1830),
    "6+6",
    np.where(
        (df_nuevos_PT["Tipo de madera"] == "C") & (df_nuevos_PT["Largo"] == 2440),
        "8+8",
        np.where(
            df_nuevos_PT["Familia"] == "CP",
            np.where(
                df_nuevos_PT["Largo"] >= 1200,
                "4+4+4",
                np.where(
                    df_nuevos_PT["Largo"] == 1100,
                    "",
                    np.where(
                        df_nuevos_PT["Largo"] == 1118,
                        "",
                        "3+3+3"
                    )
                )
            ),
            ""
        )
    )
)


#RendVolCalc
df_nuevos_PT["RendVolCalc"] = np.where(
    df_nuevos_PT["Familia"] == "CP",
    (
        df_nuevos_PT["Espesor"] * df_nuevos_PT["Ancho"] * df_nuevos_PT["Largo"] *
        (df_nuevos_PT["LargoPPCalc"] / df_nuevos_PT["Largo"]).round(0)
    ) / (
        df_nuevos_PT["EspesorPPCalc"] * df_nuevos_PT["AnchoPPCalc"] * df_nuevos_PT["LargoPPCalc"]
    ),
    (
        df_nuevos_PT["Espesor"] * df_nuevos_PT["Ancho"]
    ) / (
        df_nuevos_PT["EspesorPPCalc"] * df_nuevos_PT["AnchoPPCalc"]
    )
)


# 7- CodigoPP

esp = df_nuevos_PT["EspesorPPCalc"].astype(int).astype(str)
anc = df_nuevos_PT["AnchoPPCalc"].astype(int).astype(str)
lar = df_nuevos_PT["LargoPPCalc"].astype(int).astype(str)
kerf = df_nuevos_PT["Kerf"].astype(str)

base = esp + anc + lar + kerf

df_nuevos_PT["CodigoPP"] = np.select(
    [
        df_nuevos_PT["Familia"] == "BK",
        df_nuevos_PT["Familia"] == "PF"
    ],
    [
        "RP" + base,
        "MA" + base
    ],
    default=df_nuevos_PT["Familia"].astype(str) + base
)

# 8- PrecodPP
base2 = esp + anc
df_nuevos_PT["PrecodPP"] = np.select(
    [
        df_nuevos_PT["Familia"] == "BK",
        df_nuevos_PT["Familia"] == "PF"
    ],
    [
        "RP" + base2,
        "MA" + base2
    ],
    default=df_nuevos_PT["Familia"].astype(str) + base2
)

# 9 - Escuadria
df_nuevos_PT.loc[:, "Escuadria"] = (
    df_nuevos_PT["Familia"].astype(str)
    + " " + df_nuevos_PT["EspesorPPCalc"].astype(int).astype(str)+"x"
    + df_nuevos_PT["AnchoPPCalc"].astype(int).astype(str)
)


# 10 - Calidad
map_calidad = {
    "PA": "Pallet",
    "PR": "Premium",
    "ST": "Standard",
    "SP": "Standard Plus",
    "PM": "Pallet",
    "MA": "Machimbre",
    "EN": "G2 Standard Plus",
    "AE": "Excedente",
    "EM": "Excedente",
    "CP": "Comp. Pallet",
    "CH": "Comp. Pallet",
    "CO":"COL"
}

df_nuevos_PT["Calidad2"] = np.where(
    df_nuevos_PT["Familia"] == "BK",
    "Blank",

    np.where(
        df_nuevos_PT["Familia"] == "MU",
        "COL",

        np.where(
            (df_nuevos_PT["Familia"] == "CP") | (df_nuevos_PT["Objeto"] == "1524863"),
            "Comp. Pallet",
            df_nuevos_PT["Calidad"].map(map_calidad).fillna("ver")
        )
    )
)


#11- CodAgrup
df_nuevos_PT["CodAgrup"] = np.where(
    (df_nuevos_PT["Familia"] == "MU") & (df_nuevos_PT["Terminación"] == "RGH"),
    df_nuevos_PT["Espesor"].astype(int).astype(str),
    df_nuevos_PT["Objeto"]
)

df_nuevos_PT = df_nuevos_PT.drop(columns=["Calidad"])
df_nuevos_PT = df_nuevos_PT.rename(columns={"Calidad2": "Calidad"})
#12 Familia Postiza
Map = {
    'PF': 'MA',
    'BK': 'RP',
    'BL': 'RP',
    'MA': 'MA',
    'CP': 'CP'
}

df_nuevos_PT.loc[:, "FamiliaPostiza"] = np.where(
    df_nuevos_PT["Familia"] == "MU",
    np.where(
        df_nuevos_PT["Terminación"] == "RGH",
        "MU",
        "MUX"
    ),
    df_nuevos_PT["Familia"].map(Map)
)
df_nuevos_PT=df_nuevos_PT[['Objeto', 'Denomin.', 'Tipo de madera', 'Familia', 'Calidad',
       'Terminación', 'Grado', 'Espesor', 'Ancho', 'Largo', 'EspesorPPCalc',
       'AnchoPPCalc', 'LargoPPCalc', 'Kerf', 'RendVolCalc',
       'CodigoPP', 'PrecodPP', 'Escuadria','CodAgrup',"FamiliaPostiza"]]
#12- Status
df_nuevos_PT['Status']=True

df_nuevos_PT

,Objeto,Denomin.,Tipo de madera,Familia,Calidad,Terminación,Grado,Espesor,Ancho,Largo,...,AnchoPPCalc,LargoPPCalc,Kerf,RendVolCalc,CodigoPP,PrecodPP,Escuadria,CodAgrup,FamiliaPostiza,Status
7384,1521007,PTLMUMERGSEEX 17x125x2440 312,L,MU,COL,RGH,EX,17.0,125.0,2440.0,...,130.0,0.0,,0.908120,MU181300,MU18130,MU 18x130,17,MU,True
9933,1524350,PTCMAPMRGSEG1 17x125x2440 312,C,MA,Pallet,RGH,G1,17.0,125.0,2440.0,...,130.0,4880.0,8+8,0.908120,MA1813048808+8,MA18130,MA 18x130,1524350,MA,True
10279,1524911,PTCCPUSRGSEG1 17x80x1100 893,C,CP,Comp. Pallet,RGH,G1,17.0,80.0,1100.0,...,83.0,3355.0,,0.895385,CP18833355,CP1883,CP 18x83,1524911,CP,True
15086,1500752,PTCPFMAS4SEG2 1x6x8 280,C,PF,Machimbre,S4,G2,22.0,147.0,2440.0,...,156.0,4880.0,8+8,0.797337,MA2615648808+8,MA26156,PF 26x156,1500752,MA,True

## Tabla Maestra productos Proceso a csv

In [19]:
import pandas as pd
import numpy as np
df=pd.read_excel(r"C:\Users\horacio.brites\OneDrive - ARAUCO\DW Qlik\DataExcels\TablaMaestra.xlsx",sheet_name="TablaMaestraPP")
df["Ancho"] = df["Ancho"].fillna(0)
df["Escuadria"] = np.where(
    df["Denomin."].str.contains("PPLMUMX", na=False),
    "MUX "
    + df["Espesor"].astype(int).astype(str)
    + "x"
    + df["Ancho"].astype(int).astype(str),
    
    df["PrecodPP"].str[:2]
    + " "
    + df["Espesor"].astype(int).astype(str)
    + "x"
    + df["Ancho"].astype(int).astype(str)
)

df['Status']=True
df.to_csv(r"C:\Users\horacio.brites\OneDrive - ARAUCO\DW Qlik\DataExcels\TablaMaestraPP.csv",index=False,encoding="utf-8",sep=";")

## Codificacion Productos Proceso

In [29]:
#Materiales que comienzan con PP
df_nuevos_PP.drop(columns=['Largo','Terminación','Grado'], inplace=True)
df_nuevos_PP["Kerf"] = np.where(
    df_nuevos_PP["Denomin."].str.contains(r"\+", na=False),
    df_nuevos_PP["Denomin."].str.split("x").str[-1],
    ""
)
df_nuevos_PP["Precod"] = np.where(
    df_nuevos_PP["Denomin."].str.contains("PPLMUMX", na=False),
    
    "MUX "
    + df_nuevos_PP["Espesor"].astype(int).astype(str)
    + df_nuevos_PP["Ancho"].astype(int).astype(str),
    
    df_nuevos_PP["Familia"].astype(str)
    + df_nuevos_PP["Espesor"].astype(int).astype(str)
    + df_nuevos_PP["Ancho"].astype(int).astype(str)
)

df_nuevos_PP["Escuadria"] = np.where(
    df_nuevos_PP["Denomin."].str.contains("PPLMUMX", na=False),
    
    "MUX "
    + df_nuevos_PP["Espesor"].astype(int).astype(str)
    + "x"
    + df_nuevos_PP["Ancho"].astype(int).astype(str),
    
    df_nuevos_PP["Familia"].astype(str)
    + " "
    + df_nuevos_PP["Espesor"].astype(int).astype(str)
    + "x"
    + df_nuevos_PP["Ancho"].astype(int).astype(str)
)
df_nuevos_PP['Status']=True
df_nuevos_PP

,Objeto,Denomin.,Tipo de madera,Familia,Calidad,Espesor,Ancho,Kerf,Precod,Escuadria,Status
5,1205715,PPCMASPRGSESD 23x148xRL,C,MA,SP,23.0,148.0,,MA23148,MA 23x148,True
94,1205835,PPCMASPRGVESD 28x104x4880,C,MA,SP,28.0,104.0,,MA28104,MA 28x104,True
1181,1207980,PPLMUPRRGVESD 18x104xRL,L,MU,PR,18.0,104.0,,MU18104,MU 18x104,True
1862,1209155,PPCMASPRGVESD 23x148x6+6,C,MA,SP,23.0,148.0,6+6,MA23148,MA 23x148,True
2148,1209732,PPLMUMXRGSESD 23x151xRL,L,MU,MX,23.0,151.0,,MUX 23151,MUX 23x151,True
2250,1209896,PPCCPUSRGVESD 18x83x11,C,CP,US,18.0,83.0,,CP1883,CP 18x83,True
2315,1210019,PPLRPPCRGSESD 38x119xRL,L,RP,PC,38.0,119.0,,RP38119,RP 38x119,True
2333,1210082,PPCCPPARGSESD 16x140x3+3+3,C,CP,PA,16.0,140.0,3+3+3,CP16140,CP 16x140,True